# Generated by Django 3.2.5 on 2021-08-10 04:33

from django.db import migrations, models
import django.db.models.deletion
import parcels.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0032_alter_tenant_pin_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrived', models.DateTimeField(auto_now_add=True, null=True)),
                ('parcel_num', models.CharField(default=parcels.models.parcel_num_generator, max_length=6)),
                ('flat_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='property.flat')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='property.concierge')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='property.tenant')),
            ],
        ),
    ]
