# Generated by Django 3.2.5 on 2021-08-10 04:35

from django.db import migrations, models
import parcels.models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='parcel_num',
            field=models.CharField(default=parcels.models.parcel_num_generator, max_length=8),
        ),
    ]
