# Generated by Django 3.2.5 on 2021-08-10 04:50

from django.db import migrations, models
import django.db.models.deletion
import parcels.models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0033_alter_tenant_pin_code'),
        ('parcels', '0002_alter_parcel_parcel_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='processed_by',
            new_name='received_by',
        ),
        migrations.AddField(
            model_name='parcel',
            name='additional_notes',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='parcel',
            name='is_collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parcel',
            name='picked_up_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='pickup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='released', to='property.concierge'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='parcel_num',
            field=models.CharField(default=parcels.models.parcel_num_generator, editable=False, max_length=8),
        ),
    ]
