# Generated by Django 3.2.5 on 2021-08-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0003_auto_20210810_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='pickup_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
