# Generated by Django 3.2.5 on 2021-08-10 05:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0005_alter_parcel_pickup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='amount_parcels',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
    ]
