# Generated by Django 3.2.5 on 2021-09-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0006_parcel_amount_parcels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='date_arrived',
            field=models.DateTimeField(null=True),
        ),
    ]
