# Generated by Django 3.2.5 on 2021-07-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaluser',
            name='email',
            field=models.EmailField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='portaluser',
            name='name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
