# Generated by Django 3.2.5 on 2021-07-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210727_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaluser',
            name='username',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
