# Generated by Django 3.2.5 on 2021-07-27 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_portaluser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portaluser',
            name='username',
        ),
    ]
