# Generated by Django 3.2.5 on 2021-07-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20210729_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymbookingblock',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
    ]
