# Generated by Django 3.2.5 on 2021-07-29 10:17

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_gymbookingblock_all_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymbookingblock',
            name='date',
            field=models.DateField(null=True, validators=[booking.models.validate_date]),
        ),
    ]
