# Generated by Django 3.2.5 on 2021-07-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_gymbookingblock_block_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymbookingblock',
            name='block_length',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], max_length=2, null=True),
        ),
    ]
