# Generated by Django 3.2.5 on 2021-07-30 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_gymbookingblock_block_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gymbookingblock',
            old_name='block_length',
            new_name='duration',
        ),
    ]
