# Generated by Django 3.2.5 on 2021-08-01 04:34

import booking.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0028_alter_tenant_pin_code'),
        ('booking', '0012_cinemabooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaBookingBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, validators=[booking.models.validate_date])),
                ('made_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.concierge')),
            ],
        ),
    ]
