# Generated by Django 3.2.5 on 2021-08-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_cinemabookingblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemabookingblock',
            name='additional_notes',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
