# Generated by Django 3.2.5 on 2021-07-27 04:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=5, null=True, unique=True)),
                ('business_name', models.CharField(max_length=20, null=True)),
                ('street_location', models.CharField(max_length=20, null=True)),
                ('full_address', models.CharField(blank=True, max_length=40, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('is_running', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Concierge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True, unique=True)),
                ('surname', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('work_pattern', models.CharField(choices=[('Day', 'Day'), ('Night', 'Night'), ('Other', 'Other')], max_length=6, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_number', models.CharField(choices=[('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('C7', 'C7'), ('C8', 'C8'), ('C9', 'C9'), ('C10', 'C10'), ('C11', 'C11'), ('C12', 'C12'), ('C13', 'C13'), ('C14', 'C14'), ('C15', 'C15'), ('C16', 'C16'), ('C17', 'C17'), ('C18', 'C18'), ('C19', 'C19'), ('C20', 'C20'), ('C21', 'C21'), ('C22', 'C22'), ('C23', 'C23'), ('C24', 'C24'), ('C25', 'C25'), ('C26', 'C26'), ('C27', 'C27'), ('C28', 'C28'), ('C29', 'C29'), ('C30', 'C30'), ('C31', 'C31'), ('C32', 'C32'), ('C33', 'C33'), ('C34', 'C34'), ('C35', 'C35'), ('C36', 'C36'), ('C37', 'C37'), ('C38', 'C38'), ('C39', 'C39'), ('C40', 'C40'), ('C41', 'C41'), ('C42', 'C42'), ('C43', 'C43'), ('C44', 'C44'), ('C45', 'C45'), ('C46', 'C46'), ('C47', 'C47'), ('C48', 'C48'), ('C49', 'C49'), ('C50', 'C50'), ('C51', 'C51'), ('C52', 'C52'), ('C53', 'C53'), ('C54', 'C54'), ('R1', 'R1'), ('R2', 'R2'), ('R3', 'R3'), ('R4', 'R4'), ('R5', 'R5'), ('R6', 'R6'), ('R7', 'R7'), ('R8', 'R8'), ('R9', 'R9'), ('R10', 'R10'), ('R11', 'R11'), ('R12', 'R12'), ('R13', 'R13'), ('R14', 'R14'), ('R15', 'R15'), ('R16', 'R16'), ('R17', 'R17'), ('R18', 'R18'), ('R19', 'R19'), ('R20', 'R20'), ('R21', 'R21'), ('R22', 'R22'), ('R23', 'R23'), ('R24', 'R24'), ('R25', 'R25'), ('R26', 'R26'), ('R27', 'R27'), ('R28', 'R28'), ('R29', 'R29'), ('R30', 'R30'), ('R31', 'R31'), ('R32', 'R32'), ('R33', 'R33'), ('R34', 'R34'), ('R35', 'R35'), ('R36', 'R36'), ('R37', 'R37'), ('R38', 'R38'), ('R39', 'R39'), ('R40', 'R40'), ('R41', 'R41'), ('R42', 'R42'), ('R43', 'R43'), ('R44', 'R44'), ('R45', 'R45'), ('R46', 'R46'), ('R47', 'R47'), ('R48', 'R48'), ('R49', 'R49'), ('R50', 'R50'), ('R51', 'R51'), ('R52', 'R52'), ('R53', 'R53'), ('R54', 'R54'), ('R55', 'R55'), ('R56', 'R56'), ('R57', 'R57'), ('R58', 'R58'), ('R59', 'R59'), ('R60', 'R60'), ('R61', 'R61'), ('R62', 'R62'), ('R63', 'R63'), ('R64', 'R64'), ('R65', 'R65'), ('R66', 'R66'), ('R67', 'R67'), ('R68', 'R68'), ('R69', 'R69'), ('R70', 'R70'), ('R71', 'R71'), ('R72', 'R72'), ('R73', 'R73'), ('R74', 'R74'), ('R75', 'R75'), ('R76', 'R76'), ('R77', 'R77'), ('R78', 'R78'), ('R79', 'R79'), ('R80', 'R80'), ('R81', 'R81'), ('R82', 'R82'), ('R83', 'R83'), ('R84', 'R84'), ('R85', 'R85'), ('R86', 'R86'), ('R87', 'R87'), ('R88', 'R88'), ('R89', 'R89'), ('R90', 'R90'), ('R91', 'R91'), ('R92', 'R92'), ('R93', 'R93'), ('R94', 'R94'), ('R95', 'R95'), ('R96', 'R96'), ('R97', 'R97'), ('R98', 'R98'), ('R99', 'R99'), ('R100', 'R100'), ('R101', 'R101'), ('R102', 'R102'), ('R103', 'R103'), ('R104', 'R104'), ('R105', 'R105'), ('R106', 'R106'), ('R107', 'R107'), ('R108', 'R108'), ('R109', 'R109'), ('R110', 'R110'), ('R111', 'R111'), ('R112', 'R112'), ('R113', 'R113'), ('R114', 'R114'), ('R115', 'R115'), ('R116', 'R116'), ('R117', 'R117'), ('R118', 'R118'), ('R119', 'R119'), ('R120', 'R120'), ('R121', 'R121'), ('R122', 'R122'), ('R123', 'R123'), ('R124', 'R124'), ('R125', 'R125'), ('R126', 'R126'), ('R127', 'R127'), ('R128', 'R128'), ('R129', 'R129'), ('R130', 'R130'), ('OUT', 'OUT')], max_length=4, null=True, unique=True)),
                ('building', models.CharField(choices=[('Cassia', 'Cassia'), ('Rosewood', 'Rosewood')], max_length=8, null=True)),
                ('core', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('floor', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('flat_size', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('full_address', models.CharField(blank=True, max_length=40, null=True)),
                ('flat_type', models.CharField(choices=[('Vonder', 'Vonder'), ('Anglo', 'Anglo'), ('Private', 'Private'), ('Other', 'Other')], max_length=10, null=True)),
                ('agency', models.CharField(blank=True, max_length=20, null=True)),
                ('agency_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('auth_access', models.CharField(blank=True, max_length=100)),
                ('additional_notes', models.TextField(blank=True, max_length=300)),
                ('is_empty', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True)),
                ('surname', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('status', models.CharField(choices=[('Tenant', 'Tenant'), ('Owner', 'Owner'), ('Other', 'Other')], max_length=10, null=True)),
                ('stay_length', models.CharField(max_length=20, null=True)),
                ('pet_licence', models.CharField(max_length=20, null=True)),
                ('additional_notes', models.TextField(blank=True, max_length=300)),
                ('date_moved_in', models.DateField(blank=True, null=True)),
                ('date_added', models.DateField(auto_now_add=True, null=True)),
                ('moved_out', models.BooleanField(default=False)),
                ('date_moved_out', models.DateField(blank=True, null=True)),
                ('pin_code', models.CharField(blank=True, default='SE1671', editable=False, max_length=6)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='property.flat')),
            ],
            options={
                'unique_together': {('name', 'surname')},
            },
        ),
    ]
