# Generated by Django 3.2.5 on 2021-07-25 04:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='name',
        ),
        migrations.AddField(
            model_name='flat',
            name='building',
            field=models.CharField(choices=[('Cassia', 'Cassia'), ('Rosewood', 'Rosewood')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='flat',
            name='core',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='flat',
            name='flat_number',
            field=models.CharField(choices=[('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('R1', 'R1'), ('R2', 'R2'), ('R3', 'R3')], max_length=4, null=True, unique=True),
        ),
    ]
