# Generated by Django 3.2.5 on 2021-07-25 04:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20210725_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='floor',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
