# Generated by Django 3.2.5 on 2021-07-25 05:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='additional_notes',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='flat',
            name='auth_access',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='flat',
            name='flat_size',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='flat',
            name='flat_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='floor',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
