# Generated by Django 3.2.5 on 2021-07-25 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20210725_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='additional_notes',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True)),
                ('surname', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('stay_length', models.CharField(max_length=20, null=True)),
                ('pet_licence', models.CharField(max_length=20, null=True)),
                ('additional_notes', models.TextField(blank=True, max_length=300)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='property.flat')),
            ],
            options={
                'unique_together': {('name', 'surname')},
            },
        ),
    ]
