# Generated by Django 3.2.5 on 2021-07-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20210725_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='phone_number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
