# Generated by Django 3.2.5 on 2021-07-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_alter_tenant_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=5, null=True)),
                ('business_name', models.CharField(max_length=20, null=True)),
                ('street_location', models.CharField(max_length=20, null=True)),
                ('full_address', models.CharField(blank=True, max_length=40, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_email', models.EmailField(max_length=50, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='flat',
            name='full_address',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
