# Generated by Django 3.2.5 on 2021-07-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_alter_commercialunit_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concierge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True, unique=True)),
                ('surname', models.CharField(blank=True, max_length=15, null=True)),
                ('work_pattern', models.CharField(choices=[('Day', 'Day'), ('Night', 'Night'), ('Other', 'Other')], max_length=6, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='flat',
            name='agency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='flat',
            name='agency_contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commercialunit',
            name='unit_number',
            field=models.CharField(max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='flat_type',
            field=models.CharField(choices=[('Vonder', 'Vonder'), ('Anglo', 'Anglo'), ('Private', 'Private'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
