# Generated by Django 3.2.5 on 2021-08-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0027_alter_tenant_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='pin_code',
            field=models.CharField(blank=True, default='se5520', editable=False, max_length=6),
        ),
    ]
