# Generated by Django 3.2.5 on 2021-08-10 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0029_alter_tenant_pin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='electric_meter',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='flat',
            name='heat_meter',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='flat',
            name='water_meter',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='pin_code',
            field=models.CharField(blank=True, default='se2226', editable=False, max_length=6),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('description', models.TextField(max_length=200, null=True)),
                ('flat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complainee', to='property.flat')),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='property.concierge')),
                ('placed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complainant', to='property.flat')),
            ],
        ),
    ]
