# Generated by Django 3.2.5 on 2021-08-10 03:47

from django.db import migrations, models
import property.models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0030_auto_20210810_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='last_reading',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='flat',
            name='last_reading_date',
            field=models.DateField(blank=True, null=True, validators=[property.models.validate_date]),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date',
            field=models.DateField(null=True, validators=[property.models.validate_date]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='pin_code',
            field=models.CharField(blank=True, default='se2751', editable=False, max_length=6),
        ),
    ]
