# Generated by Django 3.2.5 on 2021-08-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0031_auto_20210810_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='pin_code',
            field=models.CharField(default='se7312', editable=False, max_length=6),
        ),
    ]
