# Generated by Django 3.2.5 on 2021-08-10 04:35

from django.db import migrations, models
import property.models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0032_alter_tenant_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='pin_code',
            field=models.CharField(default=property.models.pin_generator, editable=False, max_length=6),
        ),
    ]
